### ISSUE TITLE
Naga Pro not on device list

### ISSUE THREAD

**Issue by juupajuupa** [FruityRazer/FruityKit#18] opened 2021-05-08 19:26 UTC
Hey, is it possible to add wireless Razer naga pro?

**Comment by edualm** [comment] 2021-05-09 19:37
I can work on that when https://github.com/openrazer/openrazer/issues/1247 is closed.

**Comment by edualm** [comment] 2021-05-09 19:38
Closing as this is a duplicate of https://github.com/FruityRazer/FruityKit/issues/14.

**Closed by edualm** 2021-05-09 19:38 UTC
Labels: waiting for openrazer
